### Get current user
GET http://localhost:5000/api/auth
Accept: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWZkMWU1YTA2OGZiYjMzNTgwYTVkODE0In0sImlhdCI6MTYwNzU5MTMyOCwiZXhwIjoxNjA3OTUxMzI4fQ.UwTGtP9DZgZ3syJyNhkFUbOq8mP1ZxmvInWAurMD_4w


### Login User
POST http://localhost:5000/api/auth
Content-Type: application/json

{
  "email": "jayhan@gmail.com",
  "password": "123456"
}

### Register User
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "name": "Tyler Lee",
  "email": "tylerlee@gmail.com",
  "password": "123456"
}

###

