### Add a post
POST http://localhost:5000/api/posts
Content-Type: application/json
x-Auth-Token: {{x-auth-token}}

{
  "text": "Let's run GraphQL"
}

### Get all posts
GET http://localhost:5000/api/posts
Content-Type: application/json
x-Auth-Token: {{x-auth-token}}

### Get posts by ID
GET http://localhost:5000/api/posts/5fd24301a9c7a83d0cf1b9ec
Content-Type: application/json
x-Auth-Token: {{x-auth-token}}

### Get posts by wrong ID
GET http://localhost:5000/api/posts/5fd24301a9c7a83d0cf1b9ec12a
Content-Type: application/json
x-Auth-Token: {{x-auth-token}}

### Get posts by ID
DELETE http://localhost:5000/api/posts/5fd2419fb474ca0ea434b647
Content-Type: application/json
x-Auth-Token: {{x-auth-token}}

### Like post
PUT http://localhost:5000/api/posts/like/5fd2413faef20c3c5cdbfb3d
Content-Type: application/json
x-Auth-Token: {{x-auth-token}}

### Unlike post
PUT http://localhost:5000/api/posts/unlike/5fd2413faef20c3c5cdbfb3d
Content-Type: application/json
x-Auth-Token: {{x-auth-token}}

### Add a comment
POST http://localhost:5000/api/posts/comment/5fd2413faef20c3c5cdbfb3d
Content-Type: application/json
x-Auth-Token: {{x-auth-token}}

{
  "text": "Thank you, great post!"
}

### Delete a comment
DELETE http://localhost:5000/api/posts/comment/5fd2413faef20c3c5cdbfb3d/5fd2fc85e45b391b38c57cfe
Content-Type: application/json
x-Auth-Token: {{x-auth-token}}

###
