### Create or Update user profile
POST http://localhost:5000/api/profile/
Content-Type: application/json
x-auth-token: {{x-auth-token}}

{
  "company": "Twitter",
  "status": "CTO",
  "website": "https://www.twitter.com",
  "skills": "HTML, CSS,JS PHP,Ruby",
  "location": "California, CA",
  "bio": "I am a developer and instructor for Traversy Media",
  "githubusername": "bradtraversy",
  "twitter": "https://twitter.com/twitter",
  "facebook": "https://facebook.com/twitter",
  "youtube": "https://youtube.com/twitter"
}

### Get current user profile
GET http://localhost:5000/api/profile/me
Accept: application/json
x-auth-token:{{x-auth-token}}

### Get all profiles
GET http://localhost:5000/api/profile
Accept: application/json

### Get profile by ID
GET http://localhost:5000/api/profile/user/5fd1eea5e70e14328c9cf82b
Accept: application/json

### Get profile by wrong ID (longer length than valid ID)
GET http://localhost:5000/api/profile/user/5fd1eea5e70e14328c9cf82baaaasd
Accept: application/json

### Delete user
DELETE http://localhost:5000/api/profile
Accept: application/json
x-auth-token:{{x-auth-token}}

### Add experience
PUT http://localhost:5000/api/profile/experience
Content-Type: application/json
x-auth-token: {{x-auth-token}}

{
  "title": "CTO",
  "company": "Tinder",
  "location": "California CA",
  "from": "8-10-2015",
  "current": false,
  "description": "Management"
}

### Delete experience
DELETE http://localhost:5000/api/profile/experience/5fd1f372923e4a1f04d98427
Content-Type: application/json
x-auth-token: {{x-auth-token}}

### Add education
PUT http://localhost:5000/api/profile/education
Content-Type: application/json
x-auth-token: {{x-auth-token}}

{
  "school": "UBC",
  "degree": "Bachelor Degree",
  "fieldofstudy": "CS",
  "from": "8-10-2019",
  "current": true,
  "description": "Study computer science"
}

### Delete education
DELETE http://localhost:5000/api/profile/education/5fd1f5568bcd8d0e40d8b6a8
Content-Type: application/json
x-auth-token: {{x-auth-token}}

###