GET http://localhost:5000/
Accept: application/json

###
GET http://localhost:5000/api/products
Accept: application/json

###
GET http://localhost:5000/api/products/3
Accept: application/json

###



